# Generated by Django 4.1.6 on 2023-04-20 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_supervisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='agent_unique_code',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
