# Generated by Django 4.1.6 on 2023-05-12 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_supervisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_approved',
            field=models.BooleanField(default=False),
        ),
    ]
