# Generated by Django 4.1.6 on 2023-04-20 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_agent_unique_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='agent_unique_code',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
