# Generated by Django 4.1.6 on 2023-05-30 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(default='', max_length=10)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
