# Generated by Django 4.1.6 on 2023-04-19 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authenticatedphoneaddress',
            old_name='phones_imei',
            new_name='phones_id',
        ),
        migrations.AddField(
            model_name='authenticatedphoneaddress',
            name='finger_print',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='authenticatedphoneaddress',
            name='phone_brand',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='authenticatedphoneaddress',
            name='phone_model',
            field=models.CharField(default='', max_length=100),
        ),
    ]
