# Generated by Django 4.1.6 on 2023-06-11 08:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilemoneydeposit',
            name='d_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
