# Generated by Django 4.1.6 on 2023-06-09 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobilemoneydeposit',
            name='total',
        ),
    ]
