# Generated by Django 4.1.6 on 2023-06-02 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_sendotp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SendOTP',
        ),
    ]
