# Generated by Django 4.1.6 on 2023-04-19 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_phones_imei_authenticatedphoneaddress_phones_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authenticatedphoneaddress',
            name='finger_print',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='authenticatedphoneaddress',
            name='phone_brand',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='authenticatedphoneaddress',
            name='phone_model',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
