# Generated by Django 4.1.6 on 2023-04-25 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_customer_id_number_remove_customer_id_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobilemoneywithdraw',
            name='id_type',
        ),
        migrations.AlterField(
            model_name='bankwithdrawal',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_withdraw_customer', to='api.customer'),
        ),
        migrations.AlterField(
            model_name='mobilemoneydeposit',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='momo_deposit_customer', to='api.customer'),
        ),
        migrations.AlterField(
            model_name='mobilemoneywithdraw',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='momo_withdrawal_customer', to='api.customer'),
        ),
    ]
