# Generated by Django 4.1.6 on 2023-05-15 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_agentaccounts_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentaccounts',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_creating_account', to=settings.AUTH_USER_MODEL),
        ),
    ]
