# Generated by Django 4.1.6 on 2023-06-11 08:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_mobilemoneydeposit_d_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilemoneywithdraw',
            name='d_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
