# Generated by Django 4.1.6 on 2023-06-11 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_mobilemoneywithdraw_d_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilemoneydeposit',
            name='d_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='mobilemoneywithdraw',
            name='d_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
