# Generated by Django 4.1.6 on 2023-06-02 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_delete_sendotp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobilemoneywithdraw',
            name='d_1',
        ),
        migrations.RemoveField(
            model_name='mobilemoneywithdraw',
            name='d_10',
        ),
        migrations.RemoveField(
            model_name='mobilemoneywithdraw',
            name='d_100',
        ),
        migrations.RemoveField(
            model_name='mobilemoneywithdraw',
            name='d_2',
        ),
        migrations.RemoveField(
            model_name='mobilemoneywithdraw',
            name='d_20',
        ),
        migrations.RemoveField(
            model_name='mobilemoneywithdraw',
            name='d_200',
        ),
        migrations.RemoveField(
            model_name='mobilemoneywithdraw',
            name='d_5',
        ),
        migrations.RemoveField(
            model_name='mobilemoneywithdraw',
            name='d_50',
        ),
        migrations.RemoveField(
            model_name='mobilemoneywithdraw',
            name='total',
        ),
    ]
