# Generated by Django 4.1.6 on 2023-04-25 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_mobilemoneywithdraw_id_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilemoneydeposit',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=19),
        ),
    ]
