# Generated by Django 4.1.6 on 2023-06-03 08:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_remove_mobilemoneywithdraw_d_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerMtnPayTo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_or_merchant', models.CharField(default='', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=19)),
                ('reference', models.CharField(blank=True, default='', max_length=100)),
                ('pay_to_type', models.CharField(choices=[('Select pay to Type', 'Select pay to Type'), ('Agent', 'Agent'), ('Merchant', 'Merchant')], default='Agent', max_length=50)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_making_pay_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
