# Generated by Django 4.1.6 on 2023-05-16 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_setupmeeting_agent_holdaccounts_merchant_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='setupmeeting',
            name='meeting_link',
            field=models.CharField(default='', max_length=255),
        ),
    ]
