# Generated by Django 4.1.6 on 2023-05-21 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_reports_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_reports', to=settings.AUTH_USER_MODEL),
        ),
    ]
