# Generated by Django 4.1.6 on 2023-04-25 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_mobilemoneydeposit_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdeposit',
            name='customer',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='bankwithdrawal',
            name='customer',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='mobilemoneydeposit',
            name='customer',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='mobilemoneywithdraw',
            name='customer',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
