# Generated by Django 4.1.6 on 2023-06-20 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_mobilemoneydeposit_d_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckAppVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_version', models.IntegerField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
