# Generated by Django 4.1.6 on 2023-05-21 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0006_alter_reports_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentaccountsbalancestarted',
            name='close_physical',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=19),
        ),
        migrations.AddField(
            model_name='agentaccountsbalancestarted',
            name='closed_e_cash_total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=19),
        ),
        migrations.AddField(
            model_name='agentaccountsbalancestarted',
            name='closed_mtn_e_cash',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=19),
        ),
        migrations.AddField(
            model_name='agentaccountsbalancestarted',
            name='closed_tigo_airtel_e_cash',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=19),
        ),
        migrations.AddField(
            model_name='agentaccountsbalancestarted',
            name='closed_vodafone_e_cash',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=19),
        ),
        migrations.AddField(
            model_name='agentaccountsbalancestarted',
            name='isClosed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agentaccountsbalancestarted',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owner_started_accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='AgentAccountsBalanceClosed',
        ),
    ]
