# Generated by Django 4.1.6 on 2023-05-16 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_setupmeeting_meeting_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setupmeeting',
            name='meeting_link',
            field=models.CharField(default='', max_length=500),
        ),
    ]
