# Generated by Django 4.1.6 on 2023-04-26 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_bankdeposit_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobilemoneywithdraw',
            name='id_number',
        ),
    ]
