# Generated by Django 4.1.6 on 2023-06-24 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_checkappversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankwithdrawal',
            name='withdrawal_month',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='bankwithdrawal',
            name='withdrawal_year',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
