# Generated by Django 4.1.6 on 2023-06-03 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_ownermtnpayto'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilemoneydeposit',
            name='deposited_month',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='mobilemoneydeposit',
            name='deposited_year',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='mobilemoneywithdraw',
            name='withdrawal_month',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='mobilemoneywithdraw',
            name='withdrawal_year',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
