# Generated by Django 4.1.6 on 2023-04-26 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_mobilemoneywithdraw_id_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankdeposit',
            name='depositor_number',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='bankdeposit',
            name='depositor_name',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
