# Generated by Django 4.1.6 on 2023-07-04 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_checkownerappversion_logintracker'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentrequest',
            name='request_type',
            field=models.CharField(choices=[('Network', 'Network'), ('Bank', 'Bank'), ('Cash', 'Cash')], default='Network', max_length=20),
        ),
    ]
