# Generated by Django 4.1.6 on 2023-05-21 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0008_alter_agentaccountsbalancestarted_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentaccountsbalancestarted',
            name='close_physical',
        ),
        migrations.RemoveField(
            model_name='agentaccountsbalancestarted',
            name='closed_e_cash_total',
        ),
        migrations.RemoveField(
            model_name='agentaccountsbalancestarted',
            name='closed_mtn_e_cash',
        ),
        migrations.RemoveField(
            model_name='agentaccountsbalancestarted',
            name='closed_tigo_airtel_e_cash',
        ),
        migrations.RemoveField(
            model_name='agentaccountsbalancestarted',
            name='closed_vodafone_e_cash',
        ),
        migrations.RemoveField(
            model_name='agentaccountsbalancestarted',
            name='isClosed',
        ),
        migrations.RemoveField(
            model_name='agentaccountsbalancestarted',
            name='owner',
        ),
        migrations.CreateModel(
            name='AgentAccountsBalanceClosed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('physical', models.DecimalField(decimal_places=2, max_digits=19)),
                ('mtn_e_cash', models.DecimalField(decimal_places=2, max_digits=19)),
                ('tigo_airtel_e_cash', models.DecimalField(decimal_places=2, max_digits=19)),
                ('vodafone_e_cash', models.DecimalField(decimal_places=2, max_digits=19)),
                ('e_cash_total', models.DecimalField(blank=True, decimal_places=2, max_digits=19)),
                ('isClosed', models.BooleanField(default=False)),
                ('date_closed', models.DateField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
