# Generated by Django 4.1.6 on 2023-04-26 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_bankdeposit_depositor_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraccounts',
            name='customer',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
