# Generated by Django 4.1.6 on 2023-04-26 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_customeraccounts_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankwithdrawal',
            name='id_number',
        ),
        migrations.RemoveField(
            model_name='bankwithdrawal',
            name='id_type',
        ),
    ]
