# Generated by Django 4.1.6 on 2023-07-21 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_agentrequest_request_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addedtoapprovedrebalancing',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='addedtoapprovedrebalancing',
            name='rebalancing',
        ),
        migrations.RemoveField(
            model_name='addedtoapprovedrequest',
            name='agent_request',
        ),
        migrations.RemoveField(
            model_name='addedtoapprovedrequest',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='agentaccounts',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='agentaccounts',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='agentrebalancing',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='agentrebalancing',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='agentrequest',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='agentrequest',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='agentrequestlimit',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='agentrequestlimit',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='agentrequestpayment',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='agentrequestpayment',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='logintracker',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='paymentforrebalancing',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='paymentforrebalancing',
            name='owner',
        ),
        migrations.DeleteModel(
            name='AddedToApprovedPayment',
        ),
        migrations.DeleteModel(
            name='AddedToApprovedReBalancing',
        ),
        migrations.DeleteModel(
            name='AddedToApprovedRequest',
        ),
        migrations.DeleteModel(
            name='AgentAccounts',
        ),
        migrations.DeleteModel(
            name='AgentReBalancing',
        ),
        migrations.DeleteModel(
            name='AgentRequest',
        ),
        migrations.DeleteModel(
            name='AgentRequestLimit',
        ),
        migrations.DeleteModel(
            name='AgentRequestPayment',
        ),
        migrations.DeleteModel(
            name='LoginTracker',
        ),
        migrations.DeleteModel(
            name='PaymentForReBalancing',
        ),
    ]
