# Generated by Django 4.1.6 on 2023-04-27 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_bankwithdrawal_id_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fraud',
            name='customer',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
