# Generated by Django 4.1.6 on 2023-05-17 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_groupownermessage_owners'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownerchat',
            name='administrator',
        ),
        migrations.RemoveField(
            model_name='ownerchat',
            name='owners',
        ),
        migrations.RemoveField(
            model_name='groupownermessage',
            name='owners',
        ),
        migrations.DeleteModel(
            name='AgentsChat',
        ),
        migrations.DeleteModel(
            name='OwnerChat',
        ),
    ]
