# Generated by Django 4.1.6 on 2023-07-23 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_agentandowneraccounts_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankdeposit',
            name='d_1',
        ),
        migrations.RemoveField(
            model_name='bankdeposit',
            name='d_10',
        ),
        migrations.RemoveField(
            model_name='bankdeposit',
            name='d_100',
        ),
        migrations.RemoveField(
            model_name='bankdeposit',
            name='d_2',
        ),
        migrations.RemoveField(
            model_name='bankdeposit',
            name='d_20',
        ),
        migrations.RemoveField(
            model_name='bankdeposit',
            name='d_200',
        ),
        migrations.RemoveField(
            model_name='bankdeposit',
            name='d_5',
        ),
        migrations.RemoveField(
            model_name='bankdeposit',
            name='d_50',
        ),
        migrations.RemoveField(
            model_name='bankdeposit',
            name='total',
        ),
        migrations.RemoveField(
            model_name='bankwithdrawal',
            name='d_1',
        ),
        migrations.RemoveField(
            model_name='bankwithdrawal',
            name='d_10',
        ),
        migrations.RemoveField(
            model_name='bankwithdrawal',
            name='d_100',
        ),
        migrations.RemoveField(
            model_name='bankwithdrawal',
            name='d_2',
        ),
        migrations.RemoveField(
            model_name='bankwithdrawal',
            name='d_20',
        ),
        migrations.RemoveField(
            model_name='bankwithdrawal',
            name='d_200',
        ),
        migrations.RemoveField(
            model_name='bankwithdrawal',
            name='d_5',
        ),
        migrations.RemoveField(
            model_name='bankwithdrawal',
            name='d_50',
        ),
        migrations.RemoveField(
            model_name='bankwithdrawal',
            name='total',
        ),
    ]
