# Generated by Django 4.1.6 on 2023-07-23 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_bankdeposit_d_1_remove_bankdeposit_d_10_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentandowneraccounts',
            name='mtn_linked_number',
            field=models.CharField(default='', max_length=100),
        ),
    ]
