# Generated by Django 4.1.6 on 2023-04-30 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0013_registeredforfloat'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentAccountsBalanceStarted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('physical', models.DecimalField(decimal_places=2, max_digits=19)),
                ('mtn_e_cash', models.DecimalField(decimal_places=2, max_digits=19)),
                ('tigo_airtel_e_cash', models.DecimalField(decimal_places=2, max_digits=19)),
                ('vodafone_e_cash', models.DecimalField(decimal_places=2, max_digits=19)),
                ('e_cash_total', models.DecimalField(blank=True, decimal_places=2, max_digits=19)),
                ('isStarted', models.BooleanField(default=False)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AgentAccountsBalanceClosed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('physical', models.DecimalField(decimal_places=2, max_digits=19)),
                ('mtn_e_cash', models.DecimalField(decimal_places=2, max_digits=19)),
                ('tigo_airtel_e_cash', models.DecimalField(decimal_places=2, max_digits=19)),
                ('vodafone_e_cash', models.DecimalField(decimal_places=2, max_digits=19)),
                ('e_cash_total', models.DecimalField(blank=True, decimal_places=2, max_digits=19)),
                ('isClosed', models.BooleanField(default=False)),
                ('date_closed', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
