# Generated by Django 4.1.6 on 2023-05-01 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_monthlypayments_freetrial_authenticateagentphone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freetrial',
            name='end_date',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='monthlypayments',
            name='end_date',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
