# Generated by Django 4.1.6 on 2023-05-01 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_freetrial_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freetrial',
            name='start_date',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
