# Generated by Django 4.1.6 on 2023-05-01 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_freetrial_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freetrial',
            name='trial_started',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='monthlypayments',
            name='start_date',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
