# Generated by Django 4.1.6 on 2023-05-02 16:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_freetrial_trial_started_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentaccountsbalancestarted',
            name='time_posted',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='agentaccountsbalancestarted',
            name='date_posted',
            field=models.DateField(auto_now_add=True),
        ),
    ]
