# Generated by Django 4.1.6 on 2023-05-02 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_agentaccountsbalancestarted_time_posted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentaccountsbalancestarted',
            name='time_posted',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
