# Generated by Django 4.1.6 on 2024-01-25 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0019_requestfloat_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestfloat',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_requesting_for_float', to=settings.AUTH_USER_MODEL),
        ),
    ]
