# Generated by Django 4.1.6 on 2023-05-03 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_customer_customer_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilemoneydeposit',
            name='type',
            field=models.CharField(blank=True, choices=[('Loading', 'Loading'), ('Direct', 'Direct'), ('Agent to Agent', 'Agent to Agent')], default='', max_length=20),
        ),
    ]
