# Generated by Django 4.1.6 on 2024-01-25 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_payrequestedfloat_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payrequestedfloat',
            name='float_request',
        ),
    ]
