# Generated by Django 4.1.6 on 2023-05-03 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_mobilemoneydeposit_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='digital_address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='location',
        ),
        migrations.AlterField(
            model_name='mobilemoneydeposit',
            name='type',
            field=models.CharField(blank=True, choices=[('Select deposit type', 'Select deposit type'), ('Loading', 'Loading'), ('Direct', 'Direct'), ('Agent to Agent', 'Agent to Agent')], default='', max_length=20),
        ),
    ]
