# Generated by Django 4.1.6 on 2024-01-25 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_remove_payrequestedfloat_float_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrequestedfloat',
            name='mode_of_payment1',
            field=models.CharField(blank=True, choices=[('Select mode of payment', 'Select mode of payment'), ('Bank Payment', 'Bank Payment'), ('Mtn', 'Mtn'), ('AirtelTigo', 'AirtelTigo'), ('Vodafone', 'Vodafone'), ('Momo pay', 'Momo pay'), ('Agent to Agent', 'Agent to Agent'), ('Cash left @', 'Cash left @'), ('Own Accounts', 'Own Accounts'), ('Company Accounts', 'Company Accounts')], default='', max_length=30),
        ),
    ]
