# Generated by Django 4.1.6 on 2023-05-03 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_remove_customer_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_pic',
            field=models.ImageField(default='default_user.png', upload_to='customer_pics'),
        ),
    ]
