# Generated by Django 4.1.6 on 2023-05-03 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_customer_customer_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_pic',
            field=models.ImageField(upload_to='customer_pics'),
        ),
    ]
