# Generated by Django 4.1.6 on 2023-05-03 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_customer_customer_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='unique_code',
            field=models.CharField(default='', max_length=500),
        ),
    ]
