# Generated by Django 4.1.6 on 2023-05-03 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_customer_unique_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='customer_pic',
        ),
    ]
