# Generated by Django 4.1.6 on 2023-05-03 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_remove_customer_customer_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='unique_code',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
