# Generated by Django 4.1.6 on 2023-05-05 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_alter_customer_unique_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeraccounts',
            name='branch',
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_pic',
            field=models.ImageField(blank=True, default='', upload_to='customers_pics'),
        ),
    ]
