# Generated by Django 4.1.6 on 2023-05-05 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_remove_customeraccounts_branch_customer_customer_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_pic',
            field=models.ImageField(default='default_user.png', upload_to='customers_pics'),
        ),
    ]
