# Generated by Django 4.1.6 on 2023-05-08 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0033_alter_customer_customer_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='MtnPayTo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(blank=True, default='', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('pay_to_type', models.CharField(choices=[('Select pay to Type', 'Select pay to Type'), ('Agent', 'Agent'), ('Merchant', 'Merchant')], default='Agent', max_length=50)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
