# Generated by Django 4.1.6 on 2023-05-08 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_mtnpayto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_pic',
            field=models.ImageField(blank=True, default='default_user.png', upload_to='customers_pics'),
        ),
    ]
