# Generated by Django 4.1.6 on 2023-05-11 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_agentrequestlimit_agentrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentrequest',
            name='payment_approved',
            field=models.BooleanField(default=False),
        ),
    ]
