# Generated by Django 4.1.6 on 2023-05-12 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0037_agentrequest_payment_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilemoneydeposit',
            name='cash_received',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=19),
        ),
        migrations.AddField(
            model_name='mobilemoneywithdraw',
            name='customer_pic',
            field=models.ImageField(blank=True, default='default_user.png', upload_to='customers_pics'),
        ),
        migrations.CreateModel(
            name='SetUpMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('date_of_meeting', models.CharField(max_length=20)),
                ('time_of_meeting', models.CharField(max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('administrator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin', to=settings.AUTH_USER_MODEL)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
