# Generated by Django 4.1.6 on 2023-05-12 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_mobilemoneydeposit_cash_received_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilemoneywithdraw',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=19),
        ),
    ]
