# Generated by Django 4.1.6 on 2023-05-13 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_remove_mobilemoneywithdraw_customer_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mobilemoneydeposit',
            old_name='amount',
            new_name='amount_sent',
        ),
        migrations.RenameField(
            model_name='mobilemoneywithdraw',
            old_name='amount',
            new_name='cash_paid',
        ),
        migrations.AddField(
            model_name='mtnpayto',
            name='depositor_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='mtnpayto',
            name='reference',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
