# Generated by Django 4.1.6 on 2023-05-13 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0043_complains'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complains',
            name='administrator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='admin_complaining_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='setupmeeting',
            name='administrator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='admin', to=settings.AUTH_USER_MODEL),
        ),
    ]
