# Generated by Django 4.1.6 on 2023-05-13 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_rename_depositor_name_mtnpayto_depositor_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentrequest',
            name='date_requested',
            field=models.DateField(auto_now_add=True),
        ),
    ]
