# Generated by Django 4.1.6 on 2023-05-13 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_alter_agentrequest_date_requested'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentrequest',
            name='payment_approved',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='agentrequest',
            name='request_approved',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='agentrequest',
            name='request_paid',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending')], default='Pending', max_length=20),
        ),
    ]
