# Generated by Django 4.1.6 on 2023-05-14 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_agentrequestpayment_addedtoapprovedrequest_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentrequest',
            name='payment_approved',
        ),
    ]
