# Generated by Django 4.1.6 on 2023-05-14 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_remove_agentrequest_payment_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentrebalancing',
            name='branch',
        ),
    ]
