# Generated by Django 4.1.6 on 2023-05-14 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_remove_agentrebalancing_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentrebalancing',
            name='request_approved',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending')], default='Pending', max_length=20),
        ),
    ]
