# Generated by Django 4.1.6 on 2023-05-14 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0052_agentrebalancing_request_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentrebalancing',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='agents_owner_rebalancing', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AddedToApprovedReBalancing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_approved', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents_owners', to=settings.AUTH_USER_MODEL)),
                ('rebalancing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.agentrebalancing')),
            ],
        ),
    ]
